#
# Module manifest for module 'IntelliTect.PSToolbox'
#
# Generated by: IntelliTect
#
# Generated on: 12/15/2022
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''

    # Version number of this module.
    ModuleVersion     = '2.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID              = '91500afc-48ad-41a6-9cdc-091bc89611ed'

    # Author of this module
    Author            = 'IntelliTect'

    # Company or vendor of this module
    CompanyName       = 'IntelliTect'

    # Copyright statement for this module
    Copyright         = '(c) IntelliTect. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Umbrella module that installs IntelliTect''s maintained PowerShell modules: IntelliTect.Common, IntelliTect.File, IntelliTect.Git, and IntelliTect.CredentialManager.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '7.2'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        'IntelliTect.Common',
        'IntelliTect.File',
        'IntelliTect.Git',
        'IntelliTect.CredentialManager'
    )

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module.
            Tags = @('IntelliTect', 'PSToolbox', 'Umbrella')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/IntelliTect/PSToolbox/blob/main/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/IntelliTect/PSToolbox'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
2.0.0  (Path B modernization)
  This is a breaking-change major release.

  Removed modules (use the recommended replacements):
    - AzureManagement                  -> Az
    - IntelliTect.PSDbxCli             -> dbxcli directly
    - IntelliTect.PSDropbin            -> Dropbox.Api SDK
    - IntelliTect.PSRestore            -> built-in Windows recycle bin / Recycle module
    - IntelliTect.ResharperNugetSearch -> NuGet/Find-Package
    - IntelliTect.MicrosoftWord        -> use Word COM/OpenXML directly
    - IntelliTect.Google               -> Google APIs PowerShell module
    - IntelliTect.ChatGpt              -> PowerShellAI module
    - DotNetCore                       -> dotnet CLI directly

  Retained and modernized modules:
    - IntelliTect.Common 2.0.0
    - IntelliTect.File 2.0.0
    - IntelliTect.Git 2.0.0
    - IntelliTect.CredentialManager (unchanged)

  Minimum PowerShell version raised to 7.2.

  The 1.x history is preserved at tag v1.0-legacy and branch legacy/v1.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

