#
# Module manifest for module 'IntelliTect.File'
#
# Generated by: Mark Michleis
#
# Generated on: 2018-07-18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'IntelliTect.File.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'e53c95a2-c105-4910-b0d5-3067a6a9d7a7'

# Author of this module
Author = 'Mark Michaelis'

# Company or vendor of this module
CompanyName = 'IntelliTect'

# Copyright statement for this module
# Copyright = ''

# Description of the functionality provided by this module
Description = 'Cmdlets for managing files with PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('IntelliTect.Common') 

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
#FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module.
        Tags = @('IntelliTect', 'File', 'Utility')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/IntelliTect/PSToolbox/blob/main/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/IntelliTect/PSToolbox'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
2.0.0
  - Get-FileEncoding rewritten to use raw FileStream (PowerShell 7 removed
    `Get-Content -Encoding byte`). Now works on PowerShell 7+.
  - Removed n-ary Join-Path wrapper; PowerShell 7 Join-Path natively accepts
    multiple child paths.
  - Minimum PowerShell version raised to 7.2.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

