#
# Module manifest for module 'IntelliTect.ResharperNugetSearch'
#
# Generated by: Kelly
#
# Generated on: 3/20/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './IntelliTect.ResharperNugetSearch.psm1'

# Version number of this module.
ModuleVersion = '1.0.0.0'

# ID used to uniquely identify this module
GUID = '1901dc01-64da-4d5c-ad51-4a1f72f67254'

# Author of this module
Author = 'Kelly Adams'

# Company or vendor of this module
CompanyName = 'IntelliTect'

# Copyright statement for this module
Copyright = '© IntelliTect. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides functions for searching against Jet Brains'' Resharper Nuget Search API.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Search-NugetForType', 'Search-NugetForNamespace')

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('Nuget', 'JetBrains', 'Resharper', 'package', 'namespace', 'type')

        # A URL to the license for this module.
         LicenseUri = 'https://raw.githubusercontent.com/IntelliTect/PSToolbox/main/LICENSE.txt'

        # A URL to the main website for this project.
         ProjectUri = 'https://github.com/IntelliTect/PSToolbox'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
         ReleaseNotes = 'Initial release.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

