#
# Module manifest for module 'PSDropbin'
#
# Generated by: Stephen
#
# Generated on: 11/26/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = "bin\IntelliTect.PSDropbin.dll"

# Version number of this module.
ModuleVersion = '0.7.1.1'

# ID used to uniquely identify this module
GUID = '8fce8226-5028-4991-be8c-09f364dbb665'

# Author of this module
Author = 'Stephen Hoerner, Mark Michaelis, Andrew Scott, & Casey Schadewitz'

# Company or vendor of this module
CompanyName = 'IntelliTect'

# Copyright statement for this module
Copyright = '(c) 2016 IntelliTect. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
This PowerShell module permits you to access Dropbox as if it were a local drive.
	

USAGE:
Import-Module IntelliTect.PSDropbin
New-DropboxDrive Dbx
cd Dbx:


The first time that you mount a given drive, your browser will open and prompt for access.
To unmount a drive, run Remove-PSDrive -Name Dbx. The stored access token will be removed when you do so. You can also run Remove-DropboxCredential at any time to remove access tokens.


If you would like for your Dropbox drive to always be available, consider adding these commands to your PowerShell user profile (https://technet.microsoft.com/en-us/library/bb613488%28v=vs.85%29.aspx).
'@

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @("bin\Copy-Item.ps1", "bin\Move-Item.ps1", "bin\New-DropboxDrive.ps1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @("bin\ViewDefinition.ps1xml")

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @("Copy-Item", "Move-Item", "New-DropboxDrive")

# Cmdlets to export from this module
CmdletsToExport = @("Copy-DropboxToLocal", "Copy-LocalToDropbox", "Remove-DropboxCredential")

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

